name: Qodana

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      # Qodana adding checks
      checks: write
      pull-requests: write needed
      # Qodana uploading SARIF
      security-events: write
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: "Setup Python"
        uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4.7.1
        with:
          python-version: "${{ inputs.python-version }}"
          allow-prereleases: true
          cache: "pip"
          cache-dependency-path: "pyproject.toml"

      - name: "Install dependencies"
        run: python -m pip install .

      - name: Qodana Scan
        uses: JetBrains/qodana-action@95ecb19ba27e308153723e54a790e4ad908b13a0 # v2023.2.8
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}

      - uses: github/codeql-action/upload-sarif@4b6aa0b07da05d6e43d0e5f9c8596a6532ce1c85 # codeql-bundle-v2.15.3
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
